[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "NeuroKit"
version = "0.1.0"
description = "NeuroNetwork component API â€“ registration, health, state"
authors = [{name = "Billy Felton", email = "billy@example.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pika",
    "flask",
    "python-consul",
    "psutil",
]

[project.optional-dependencies]
dev = ["pytest", "black"]

[project.urls]
Homepage = "https://github.com/billyFelton/NeuroKit"
